### ISSUE TITLE
Error with spoccutils

### ISSUE THREAD

**Issue by vijaybarve** [Neetu111/Species-Range-Maps-in-R#1]
````
> devtools::install_github("ropensci/spoccutils", force = TRUE)
> library(spoccutils)
Error in library(spoccutils) : there is no package called ‘spoccutils’
````

**Comment by Neetu111** [comment]
Please use the following link to download this package:
windows: 
https://github.com/ropensci/spoccutils/releases/download/v0.1.0/spoccutils_0.1.0.zip
command to install: install.packages("spoccutils_0.1.0.zip", repos = NULL)
Mac:
https://github.com/ropensci/spoccutils/releases/download/v0.1.0/spoccutils_0.1.0.tgz
command to install: install.packages("spoccutils_0.1.0.tgz", repos = NULL)

**Comment by vijaybarve** [comment]
Thanks it worked.
